Fixes for examples
plotly/Dash.NET pull request #40
Opened 2021-10-07 19:41 UTC by plt-joey

A handful of fixes to support documentation examples

- Added defaults to giraffe config to cut down on `open`s in examples
- Allow null inputs during callbacks
- Fixed issue where the `init` of some component options were returning the wrong types

2021-10-11 06:29 UTC, kMutagene approved these changes

2021-10-11 08:16 UTC, kMutagene commented
Giraffe defaults need adaption for https://github.com/plotly/Dash.NET/pull/43

2021-10-11 08:18 UTC, kMutagene requested changes

2021-10-11 08:18 UTC, kMutagene commented on src/Dash.NET.Giraffe/DashApp.fs
> +    static member initDefault hostname =
Makes absolutely sense to have this. Can you please adapt this PR reflecting the changes of https://github.com/plotly/Dash.NET/pull/43?

2021-10-12 12:30 UTC, plt-joey commented on src/Dash.NET.Giraffe/DashApp.fs
> +    static member initDefault hostname =
updated

2021-10-12 12:34 UTC, merged